name: Handle issues
on: issues
jobs:
  handle-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo "Issue action: ${{ github.event.action }}, Issue title: ${{ github.event.issue.title }}"